### ISSUE TITLE
[Feat]: v15 disable ipv6 permanent

### ISSUE THREAD

**Issue by slonio** [wg-easy/wg-easy#1920]
### Description

In my environment, having IPv6 enabled in WireGuard configurations is a major problem. Currently, with WG-Easy v15, it is not possible to permanently disable IPv6 Any manual changes to remove IPv6 addresses or ip6tables rules from wg0.conf inside the container are overwritten every time the container restarts or the configuration is updated.
There is no setting in the web UI or environment variables in v15 to turn off IPv6 completely for both the server and clients.

### Suggested Solution

Could you please add an option to globally and permanently disable IPv6 in WG-Easy v15?
This would be extremely helpful for setups where IPv6 is not supported or causes issues, and it would prevent the need for manual edits that are always lost.

**Comment by veryniceworld** [comment]
I tried to disable the ipv6 from docker compose yaml but it doesn't work.  It also doesn't work if bridge with other docker networks without ipv6 enable.

**Comment by tomorrow-nf** [comment]
> I tried to disable the ipv6 from docker compose yaml but it doesn't work. It also doesn't work if bridge with other docker networks without ipv6 enable.

I ran into the same issue. `net.ipv6.conf.all.disable_ipv6=1` no longer works, and was actually causing failures on startup (I don't have the logs handy at the moment, apologies).

I've been fighting to make my v14 setup work on v15, but ended up reverting back to v14. I want to route all connections through my DNS server (pihole) and out through gluetun in a chained VPN setup - this way, I get full LAN access while also protecting outbound traffic, and I don't need to keep toggling VPNs while I'm out, I can just enable the single connection and forget about it. There have been a lot of great discussions on this setup over here, @saturneric in particular has provided some in-depth writeups and support as well : https://github.com/qdm12/gluetun/discussions/1192#discussioncomment-13379446

This worked great for me on v14, but v15 I couldn't connect to anything over android data (despite successful nslookups and pings). Headscale worked as well when I briefly tested that out (until I realized that it doesn't really work if I'm hosting it on the same machine I want to connect to without exposing the service, oops). The only major difference with my v14 setup vs v15 is that ipv6 is enabled, and I suspect this was causing some odd issues, though I admit networking isn't my forte so who knows.

**Comment by kaaax0815** [comment]
Please try `ghcr.io/wg-easy/wg-easy:development` and set the env var `DISABLE_IPV6` to `true`.

This is documented here https://wg-easy.github.io/wg-easy/development/advanced/config/optional-config/ for now

This will remove the ip6tables rules. wg0 (and clients) will get a ipv6 address either way, but this shouldn't be a problem. if it is i can remove that too

**Comment by BobWs** [comment]
> This will remove the ip6tables rules. wg0 (and clients) will get a ipv6 address either way, but this shouldn't be a problem. if it is i can remove that too

It would be helpful to have the option to remove the IPv6 addresses from the client table. With IPv6 disabled, it can be confusing to see these IPv6 addresses in the GUI client table and on the WireGuard client devices. Therefore, it would be great if we could delete them.

**Comment by kapuett** [comment]
Can confirm this working with `ghcr.io/wg-easy/wg-easy:development` and
```
    environment:
      DISABLE_IPV6: "true"
```
in docker-compose.yml on Debian 12 with IPv6 disabled via `sysctl`:
```
❯ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
[...]
❯ cat /etc/sysctl.d/disable_ipv6.conf
net.ipv6.conf.default.disable_ipv6=1
```
 
Relevant `docker logs`:
```
Warning: Disabling IPv6...
Disabling IPv6 in Post Up hooks...
Disabling IPv6 in Post Down hooks...
Starting WireGuard...
[...]
Config synced successfully.
Wireguard Interface wg0 started successfully.
```

**Comment by bgravato** [comment]
v15 makes wg-easy app useless on TrueNAS 24.10.2.2 with ipv6 disabled.
v14 worked great, but v15 fails to start due to ipv6 not being enabled on TrueNAS.

**Comment by kgooris** [comment]
Also have same issue on QNAP NAS. The option fixed it for me also. Thx

**Comment by kaaax0815** [comment]
> Please try `ghcr.io/wg-easy/wg-easy:development` and set the env var `DISABLE_IPV6` to `true`.
> 
> This is documented here https://wg-easy.github.io/wg-easy/development/advanced/config/optional-config/ for now
> 
> This will remove the ip6tables rules. wg0 (and clients) will get a ipv6 address either way, but this shouldn't be a problem. if it is i can remove that too

Hello everyone. I just pushed an update to the development tag. If you disable ipv6 it will also stop it from adding a ipv6 to all configs. (only for dns)

**Comment by kaaax0815** [comment]
Did someone test the new development version and test that the configs are now as expected?

**Comment by kapuett** [comment]
Pulled the new image and did nothing else. Not sure if this is what should have been different but I still have IPv6 client addresses in the GUU:
`10.8.0.2, fdcc:zzzz:yyyy:xxxx::cafe:2`

**Comment by BobWs** [comment]
I just tested the `development image` and it appears to be working. In the **GUI**, it is still not possible to **remove** the **IPv6 address**, but when connecting the client to the server, the IPv6 address no longer appears in the DNS field. If this was the intended behavior of the changes, then I can confirm that it is working as expected.

I'm not sure if it was necessary, but I added the environment variable DISABLE_IPV6 and set it to true before testing.

Here is the log output:

```
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy
====================================================
| wg-easy:  v15.0.0 |
| Node:     v22.17.0 |
| Platform: linux |
| Arch:     x64 |
====================================================
Migration complete
Warning: Disabling IPv6...
IPv6 Post Up hooks already disabled, skipping...
IPv6 Post Down hooks already disabled, skipping...
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:8094
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
Syncing Config...
$ wg syncconf wg0 <(wg-quick strip wg0)
Config synced successfully.
Wireguard Interface wg0 started successfully.
Starting Cron Job...
Cron Job started successfully.
```
Here is the docker-compose file I used:

```
version: "3.8"
services:
  wireguard-server:
    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    hostname: wg-server
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    mem_reservation: 128m
    volumes:
      - /volume1/docker/wireguard/server:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "8094:8094/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      TZ: "Europe/Berlin"
      PORT: 8094
      INSECURE: false
      DISABLE_IPV6: true
    restart: "always"
    mac_address: 02:42:c0:a8:b2:41
    networks:
      macvlan0:
        ipv4_address: 192.168.178.65
      proxy:

networks:
  macvlan0:
    external: true
  proxy:
    external: true
```
**Screenshot of the client:**
![Image](https://github.com/user-attachments/assets/753f0be3-6914-4d4c-8abc-feb592eaa146)

**Comment by kaaax0815** [comment]
To remove IPv6 from the UI too is too much work, which doesn't even benefit anything.
This will be included in the 15.1.0 release
